### ISSUE TITLE
Process destruction throws an exception on FreeBSD

### ISSUE THREAD

**Issue by battleblow** [battleblow/openjdk-jdk11u#60]
The following program

```
public
class ProcessDestroy {
    public static void main(String[] args) {
        ProcessHandle.current().children().forEach(ProcessHandle::destroy);
    }
}
```

will throw

```
Exception in thread "main" java.lang.RuntimeException: Not a directory
	at java.base/java.lang.ProcessHandleImpl.getProcessPids0(Native Method)
	at java.base/java.lang.ProcessHandleImpl.children(ProcessHandleImpl.java:423)
	at java.base/java.lang.ProcessHandleImpl.children(ProcessHandleImpl.java:402)
	at ProcessDestroy.main(ProcessDestroy.java:4)
```

This causes a number of the inbuilt tests to fail.  For example, ```test/jdk/java/lang/ProcessHandle/Basic.java```

**Comment by battleblow** [comment]
Testing a potential fix

**Comment by battleblow** [comment]
Looks good so far.  Will run all the affected test cases tomorrow to verify.

**Comment by battleblow** [comment]
Fixes the following tests:

* test/jdk/java/lang/ProcessBuilder/PipelineTest.java
* test/jdk/java/lang/ProcessHandle/PermissionTest.java
* test/jdk/java/lang/ProcessHandle/Basic.java
* test/jdk/java/lang/ProcessHandle/InfoTest.java
* test/jdk/java/lang/ProcessHandle/TreeTest.java
* test/jdk/java/lang/ProcessHandle/OnExitTest.java

**Comment by battleblow** [comment]
Fix pushed
